### ISSUE TITLE
[Bug] Documentation links don't work

### ISSUE THREAD

**Issue by OwenMelbz** [ThemeMountain/maizzle#1]
The links around the documentation link to places such as `https://maizzle.com/docs/configuration`

However these just seem to sit there?

I imagine it is meant to redirect to `https://maizzle.com/docs/configuration/` ?

**Comment by hellocosmin** [comment]
Think it’s an issue with how Netlify handles them, you’re the second person to report this. 

Give me a moment, I’ll check for something in their admin...

**Comment by hellocosmin** [comment]
Enabled Pretty URLs in Netlify, looks like they're redirecting properly now - can you please confirm?

**Comment by OwenMelbz** [comment]
Seems to be okay now :) - although would suggest that it seems weird to redirect EVERY page? would it not be possible to fix the html providing the wrong link in the first place?

**Comment by hellocosmin** [comment]
Yeah, would need to manually add a trailing slash after every URL generated by Jigsaw.

**Comment by hellocosmin** [comment]
Fixed - all documentation URLs now include a trailing slash.

**Comment by tzsk** [comment]
https://maizzle.com itself isn't working for me. It's not even loading in the browser. 😭

**Comment by OwenMelbz** [comment]
Is working okay in London!

![maizzle_email_framework_and_gmail_-_owenmelbz_and_usergroups_ _kevii_wordpress](https://user-images.githubusercontent.com/1094740/43649916-5074fd1c-9736-11e8-9cf6-d9590dc8a5d3.jpg)
