### ISSUE TITLE
Feature Request: CSS Inline for production builds

### ISSUE THREAD

**Issue by rokde** [ThemeMountain/maizzle#24]
You need to have css inline to meet various email clients. Please add an out-of-the-box way for that. Otherwise the email templates are not usable for production.

This would be a really nice feature.

**Comment by hellocosmin** [comment]
The [`npm run production`](https://maizzle.com/docs/building/#production) command is already configured to inline CSS out-of-the-box 🙂

https://github.com/ThemeMountain/maizzle/blob/03f4c2a01ad2537ab46450ccab5d5e1d376b6bb3/config.production.php#L19-L32
