### ISSUE TITLE
Adding Image Tracking Pixel Shows as Text 

### ISSUE THREAD

**Issue by tronoku** [ThemeMountain/maizzle#26]
Hello,

I'm using Litmus's tracking pixel and it's appearing in the production email as body text: 
![image](https://user-images.githubusercontent.com/4155364/48677840-f11a3780-eb48-11e8-9913-43df107eb6c7.png)

The code looks like this: `<style data-ignore-inlining>@media print{ #_t { background-image: url('https://rizen49k.emltrk.com/rizen49k?p&d={Email}');}} div.OutlookMessageHeader {background-image:url('https://rizen49k.emltrk.com/rizen49k?f&d={Email}')} table.moz-email-headers-table {background-image:url('https://rizen49k.emltrk.com/rizen49k?f&d={Email}')} blockquote #_t {background-image:url('https://rizen49k.emltrk.com/rizen49k?f&d={Email}')} #MailContainerBody #_t {background-image:url('https://rizen49k.emltrk.com/rizen49k?f&d={Email}')}</style><div id="_t"></div>
<img src="https://rizen49k.emltrk.com/rizen49k?d={Email}" width="1" height="1" border="0" alt="" />`

**Comment by hellocosmin** [comment]
Hi there,

How are you adding that to your template in Maizzle, can you share a Gist/Codepen of your Blade file? 

Also, it would be useful to know what build command you're running and how your config.*.php looks for that build. Let me know, and I'll help out :)

**Comment by hellocosmin** [comment]
Closing as stale - feel free to reopen if you have more details on this...
