### ISSUE TITLE
[Question] How to use maizzle-php in a service as an api

### ISSUE THREAD

**Issue by basghar** [ThemeMountain/maizzle#35]
Does maizzle-php exposes api functions like Node Maizzle as mentioned in https://maizzle.com/docs/nodejs/. 

```
const Maizzle = require('@maizzle/framework')

const html = Maizzle.render(`html string`, options)
```

**Comment by cossssmin** [comment]
It doesn't, it's just a build system based on the Jigsaw static site generator. This was one of the reasons for building maizzle.js.
