### ISSUE TITLE
Some way to view output of build commands 💡

### ISSUE THREAD

**Issue by sambeevors** [ThemeMountain/maizzle#36]
I'd love to be able to get some kind of output file when I run build commands, maybe something like `output.json` which just shows the build output in a JSON tree

```json
{
    "folders": {
        "emails": {
            "folders": {
                "folder_1": {
                    "folders": {},
                    "files": [
                        "email_1.html",
                        "email_2.html"
                    ]
                },
                "folder_2": {
                    "folders": {},
                    "files": [
                        "email_1.html",
                        "email_2.html",
                        "email_3.html"
                    ]
                }
            }
        },
        "css": {
            "folders": {},
            "files": [
                "extra.css",
                "main.css"
            ]
        }
    }
}
```

My particular use case is to take the build output, and attach a frontend on to it so admins can preview / approve emails before they are sent. There may be a way to do this already that I'm missing, but after scouring the docs and config files I couldn't find a solution.

Thanks for your work on this, Maizzle is great 🙌🏻

**Comment by cossssmin** [comment]
Hi Sam,

Check out the [event listeners](https://jigsaw.tighten.co/docs/event-listeners/) in Jigsaw - `afterBuild` gives you a list of output file paths.

Note: I'll be focusing exclusively on [Maizzle.js](https://maizzle.com) in the future, so the Jigsaw/PHP version won't get any new features. There isn't an `afterBuild` event _yet_ in Maizzle.js, so I'll look into adding that 👍

**Comment by sambeevors** [comment]
Thanks @cossssmin !
